name: bahga_student
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <=3.8.1"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase (Updated Versions)
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.6
  firebase_messaging: ^14.7.21
  firebase_storage: ^11.7.5
  cloud_firestore: ^4.15.7
  google_fonts: ^6.2.1
  video_player: ^2.7.0
  intl: ^0.18.0
  dio: ^5.3.2
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.0.10
  flutter_pdfview: ^1.2.1
  image_picker: ^1.1.2
#  file_picker: ^6.2.1
  open_file: ^3.5.4
  google_mlkit_face_detection: ^0.12.0
  flutter_face_api: ^7.1.267



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/assignment.png
    - assets/images/logo2.jpg
    - assets/images/student_login.gif
    - assets/images/boy.png
    - assets/icons/
    - assets/animations/Work time.gif
    - assets/images/my_face.jpg
